version: '2'
services:
  database:
    image: mysql:5.7
    command: --max_allowed_packet=32505856 --sql_mode=""
    container_name: local-mysql
    ports:
    - "3399:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
    - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./.mysql:/var/lib/mysql
